spring:
  datasource:
    url: jdbc:mysql://${MINIO_HOST:db}:${MYSQL_PORT:3306}/yout
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:adminadmin}
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8010
